### PR TITLE
Vincent Gandolfo's lab04 submission, added Iphone and IphoneWithApps classes

### PR DESCRIPTION
**Pull request by vincegando**
Vincent Gandolfo's lab04 submission, classes to draw an Iphone and IphoneWithApps

### CODE REVIEW

**Comment by alecharrell** [comment]
doesnt seem to compile, there are lots of extra files in the submission that should not be in there. Maybe try deleting the ones that are not supposed to be there?

**Comment by vincegando** [comment]
It compiles for me, and I can't figure out why it might not. What are the error messages saying? And what are the extra files?

**Comment by alecharrell** [comment]
I get this:

compile:
    [javac] Compiling 90 source files to /Users/Po/Documents/cs56/lab04/vincegando/W15-lab04/build
    [javac] /Users/Po/Documents/cs56/lab04/vincegando/W15-lab04/src/edu/ucsb/cs56/w15/drawings/vgandolfo/advanced/CoffeeCup.java:28: error: duplicate class: edu.ucsb.cs56.w15.drawings.pconrad.advanced.CoffeeCup
    [javac] public class CoffeeCup extends GeneralPathWrapper implements Shape
    [javac]        ^
    [javac] /Users/Po/Documents/cs56/lab04/vincegando/W15-lab04/src/edu/ucsb/cs56/w15/drawings/vgandolfo/advanced/House.java:26: error: duplicate class: edu.ucsb.cs56.w15.drawings.pconrad.advanced.House
    [javac] public class House extends GeneralPathWrapper implements Shape
    [javac]        ^
    [javac] /Users/Po/Documents/cs56/lab04/vincegando/W15-lab04/src/edu/ucsb/cs56/w15/drawings/vgandolfo/advanced/HouseWithWindows.java:23: error: duplicate class: edu.ucsb.cs56.w15.drawings.pconrad.advanced.HouseWithWindows
    [javac] public class HouseWithWindows extends House implements Shape
    [javac]        ^
    [javac] /Users/Po/Documents/cs56/lab04/vincegando/W15-lab04/src/edu/ucsb/cs56/w15/drawings/vgandolfo/advanced/WritePictureToFile.java:21: error: duplicate class: edu.ucsb.cs56.w15.drawings.pconrad.advanced.WritePictureToFile
    [javac] public class WritePictureToFile
    [javac]        ^
    [javac] 4 errors

BUILD FAILED

**Comment by alecharrell** [comment]
AllMyDrawings.java~, 	Iphone.java~, 	MultiPictureViewer.java~, MultiPictureComponent.java~, IphoneWithApps.java~. For some reason all these say they are in the directory

**Comment by alecharrell** [comment]
I just tried deleting all of those files though and that didn't seem to work. So maybe based on those files you can figure out why it is not working. Be sure you follow the instructions specifically, or maybe talk to the TAs about showing them it working in person on your computer because I can't get it to compile

**Comment by vincegando** [comment]
It look like it isn't working because there are duplicate files in the pconrad directory(House, Coffee Cup, HouseWithWindows, WritePictureToFile). Maybe those need to be taken out? Those were just examples so I don't need them in my submission.

**Comment by vincegando** [comment]
Ok, I think I figured it out. The files copied from pconrad into my advanced directory still have pconrad in the package name. I'll fix that now and push the changes.

**Comment by alecharrell** [comment]
ok ill take a look

**Comment by alecharrell** [comment]
looks good, nice job man!

**Comment by vincegando** [comment]
Thanks! Do you know if the TAs have started grading this yet?

**Comment by alecharrell** [comment]
I dont think they have since all the moderators are not even done looking at all of them yet, plus I think they will mark them all once they have gone over them

**Comment by alecharrell** [comment]
I think the TAs will mark them*

**Comment by vincegando** [comment]
Ok cool thanks.

**Pull request merged**
