### PR TITLE
Added a Kid class under alecharrel's directory

### PR DESCRIPTION
**Pull request by cpounds**
Chloe's lab04 submission, a class to draw a kid with a balloon.

### CODE REVIEW

**Comment by alecharrell** [comment]
I can't seem to get it to compile. Please check on this before the TAs grade it!

**Comment by cpounds** [comment]
I'm confused because it totally compiles for me. Is there something missing? Is there a specific reason it is not compiling?

**Comment by alecharrell** [comment]
I get this 

compile:
    [javac] Compiling 59 source files to /Users/Po/Documents/cs56/lab04/cpounds/W15-lab04/build
    [javac] /Users/Po/Documents/cs56/lab04/cpounds/W15-lab04/src/edu/ucsb/cs56/w15/drawings/chloepounds/advanced/MultiPictureComponent.java:64: error: cannot find symbol
    [javac] 	   AllMyDrawings.drawPicture2(g2);
    [javac] 	                ^
    [javac]   symbol:   method drawPicture2(Graphics2D)
    [javac]   location: class AllMyDrawings
    [javac] /Users/Po/Documents/cs56/lab04/cpounds/W15-lab04/src/edu/ucsb/cs56/w15/drawings/chloepounds/advanced/MultiPictureComponent.java:68: error: cannot find symbol
    [javac] 	   AllMyDrawings.drawPicture3(g2);
    [javac] 	                ^
    [javac]   symbol:   method drawPicture3(Graphics2D)
    [javac]   location: class AllMyDrawings
    [javac] /Users/Po/Documents/cs56/lab04/cpounds/W15-lab04/src/edu/ucsb/cs56/w15/drawings/chloepounds/advanced/WritePictureToFile.java:69: error: cannot find symbol
    [javac] 	 AllMyDrawings.drawPicture2(g2);
    [javac] 	              ^
    [javac]   symbol:   method drawPicture2(Graphics2D)
    [javac]   location: class AllMyDrawings
    [javac] /Users/Po/Documents/cs56/lab04/cpounds/W15-lab04/src/edu/ucsb/cs56/w15/drawings/chloepounds/advanced/WritePictureToFile.java:71: error: cannot find symbol
    [javac]       	 AllMyDrawings.drawPicture3(g2);
    [javac]       	              ^
    [javac]   symbol:   method drawPicture3(Graphics2D)
    [javac]   location: class AllMyDrawings
    [javac] 4 errors

**Comment by alecharrell** [comment]
PS: I made sure to put a note on the grading of yours, because I figured it must compile fine on yours. So don't panic, if the TA is not able to get it to compile then he should be contacting you :)

**Comment by alecharrell** [comment]
One of the other student's wouldnt compile and then he checked the package names on some of the files and they were wrong, maybe look into this?

**Comment by alecharrell** [comment]
I see the issue now, you did not follow instructions on one of the parts it seems.  We use AllMyDrawings.java for testing. It seems like you did not follow the instructions for this part. Please check them and make the changes, because the TA will not give you full credit the way it is now

**Comment by cpounds** [comment]
I figured out the issue. For some reason I didn't commit the most recent changes. And then I had changed something when I began working on lab5 so I just didnt think about the fact that those changes would only be in that branch and not master. Do I have to make another pull request?

**Comment by alecharrell** [comment]
worked out this time, no you shouldn't need to make another pull request. So long as the TAs havent gotten to it yet you should get full credit now!

**Pull request merged**
