### PR TITLE
Nicholas Poon's lab04 submission, classes to draw Basketball Court and Three Point Court 

### PR DESCRIPTION
**Pull request by nickkpoon**
ThreePointCourt extends BasketballCourt

### CODE REVIEW

**Comment by alecharrell** [comment]
looks like your code for both of your objects is just copied code from the examples.  :(

**Comment by nickkpoon** [comment]
I can assure you it is not. I based my two classes on House example. But they are very different codes. Is there some misunderstanding here?

**Comment by alecharrell** [comment]
i got it figured out for you.  For some reason there was deleted files that stayed in the repo. For instance there was, "BasketballCourtWithThreePoint.java" that was exactly the same code as the houses. We have a more automated process for grading, so if the repo is messy at all like this, then it can accidentally pull from the wrong files if the package name is in there

**Comment by nickkpoon** [comment]
Thank you so much!  Sorry for the confusion.

**Pull request merged**
